name: Docker Action Example

on:
  schedule:
    - cron: '0 0 3 * * *'  # 每天3:00
    - cron: '0 0 9 * * *'  # 每天9:00
    - cron: '0 0 15 * * *' # 每天15:00
    - cron: '0 0 21 * * *' # 每天21:00

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
      
    - name: Run Docker container
      run: |
        sudo apt install git git-lfs wget -y
        wget https://github.com/kschen202115/build_llama.cpp_docker/releases/download/0.0.1/image.tar
        docker load image.tar
        git lfs install
        git clone https://huggingface.co/runfuture/MiniCPM-2B-dpo-fp16-gguf .
        sudo chmod +x run_docker.sh
        sudo bash run_docker.sh
        
        
        
