name: Docker Action Example

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: yourdockerusername/yourrepositoryname:latest
      
    - name: Run Docker container
      run: docker run yourdockerusername/yourrepositoryname:latest echo "Hello from Docker container!"

  restart_workflow:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Trigger workflow
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: yourusername/yourrepositoryname
        event-type: trigger-workflow
        client-payload: '{"workflow_file": ".github/workflows/docker_action_example.yml"}'
