name: Docker Action Example

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
      
    - name: Run Docker container
      run: docker ps

  restart_workflow:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Trigger workflow
      uses: peter-evans/repository-dispatch@v1
      with:
        token: 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
        repository: czq202115/my_action_ai
        event-type: trigger-workflow
        client-payload: '{"workflow_file": ".github/workflows/docker_action_example.yml"}'
