name: Docker Action Example

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: pull Docker container
      run: docker ps
      
    - name: Trigger Workflow B
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data: workflows } = await github.actions.listRepoWorkflows({
            owner: context.repo.owner,
            repo: context.repo.repo
          });
          const workflowB = workflows.find(workflow => workflow.name === 'Workflow B');
          await github.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: workflowB.id
          });

