name: Docker Action test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    
    - name: Run Docker container
      run: |
        sudo apt install git git-lfs wget -y
        wget https://github.com/kschen202115/build_llama.cpp_docker/releases/download/0.0.1/image.tar
        docker load -i image.tar
        git lfs install
        mkdir models
        cd $GITHUB_WORKSPACE/models
        git clone https://huggingface.co/runfuture/MiniCPM-2B-dpo-fp16-gguf .
        cd $GITHUB_WORKSPACE
        sudo chmod +x run_docker.sh
        sudo bash run_docker.sh
        sudo docker ps -a
