name: Docker Action test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: install cloudflare
      run: |
        sudo apt install curl -y
        curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb && 
        sudo dpkg -i cloudflared.deb && 
        sudo cloudflared service install eyJhIjoiYWZjODQ0MzQ0YzNhZGE5ODM3MzgzYjFlNDQzYjg3YWEiLCJ0IjoiMTQyZDMzMWMtYWUzZC00ZGJkLThhYzktZDJlNzY2YTAxYmFiIiwicyI6Ill6YzRNRGhpWVRBdE0yRmpOQzAwWW1RNUxUbGhOVFF0WXpSbE16WmlOMlF5TXpOaiJ9
    - name: Run Docker container
      run: |
        sudo apt install git git-lfs wget -y
        wget https://github.com/kschen202115/build_llama.cpp_docker/releases/download/0.0.1/image.tar
        docker load -i image.tar
        git lfs install
        mkdir models
        cd $GITHUB_WORKSPACE/models
        git clone https://huggingface.co/runfuture/MiniCPM-2B-dpo-fp16-gguf .
        cd $GITHUB_WORKSPACE
        sudo chmod +x run_docker.sh
        sudo bash run_docker.sh
